# Generated by Django 3.1.2 on 2020-11-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=1)),
                ('estado', models.CharField(max_length=1)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fynex_app.paciente')),
            ],
        ),
    ]
