# Generated by Django 3.1.2 on 2020-11-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centromedico',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
