# Generated by Django 3.1.2 on 2020-11-18 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0003_auto_20201113_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
