# Generated by Django 3.1.2 on 2020-11-18 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0004_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_peticion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historialvariableseguimiento',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='fecha',
            field=models.DateField(),
        ),
    ]
