# Generated by Django 3.1.2 on 2020-11-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0005_auto_20201117_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('tipo_ejercicio', models.CharField(max_length=50)),
                ('ejercicio', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
                ('dias', models.CharField(max_length=50)),
                ('tiempo', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fynex_app.paciente')),
            ],
        ),
    ]
