# Generated by Django 3.1.2 on 2020-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0006_planejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableseguimiento',
            name='intervalo_referencia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='variableseguimiento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variableseguimiento',
            name='unidad',
            field=models.CharField(max_length=150),
        ),
    ]
