# Generated by Django 3.1.2 on 2020-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0007_auto_20201118_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableseguimiento',
            name='obligatorio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
