# Generated by Django 3.1.2 on 2020-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0009_auto_20201118_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejercicio',
            name='rating',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
