# Generated by Django 3.1.4 on 2021-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0011_recomendadormemoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendadormemoria',
            name='user1',
            field=models.IntegerField(),
        ),
    ]
