# Generated by Django 3.1.4 on 2021-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0013_auto_20210119_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendadormemoria',
            name='id',
        ),
        migrations.AlterField(
            model_name='recomendadormemoria',
            name='user1',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
