# Generated by Django 3.1.4 on 2021-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0014_auto_20210119_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendadormemoria',
            name='usado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
