# Generated by Django 3.1.4 on 2021-02-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0015_recomendadormemoria_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha_entrega',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
