# Generated by Django 3.1.4 on 2021-02-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0016_auto_20210209_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='notificado_email',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
