# Generated by Django 3.1.4 on 2021-03-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0017_auto_20210217_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejercicio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
