# Generated by Django 3.1.4 on 2021-03-09 23:33

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0019_auto_20210309_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=datetimeutc.fields.DateTimeUTCField(),
        ),
    ]
