# Generated by Django 3.1.4 on 2021-03-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0020_auto_20210309_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='medico',
        ),
    ]
