# Generated by Django 3.1.4 on 2021-03-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0022_plannutricional_similitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannutricional',
            old_name='similitud',
            new_name='dif_calorias',
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='dif_carbohidratos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='dif_grasas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='dif_proteinas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
