# Generated by Django 3.1.4 on 2021-03-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0023_auto_20210314_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannutricional',
            name='dif_calorias',
        ),
    ]
