# Generated by Django 3.1.4 on 2021-03-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0024_remove_plannutricional_dif_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='planejercicio',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='fecha',
            field=models.DateField(),
        ),
    ]
