# Generated by Django 3.1.4 on 2021-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0025_auto_20210314_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendadormemoria',
            old_name='usado',
            new_name='usado_ejercicio',
        ),
        migrations.AddField(
            model_name='recomendadormemoria',
            name='usado_nutricion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
