# Generated by Django 3.1.4 on 2021-03-15 23:21

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0027_auto_20210314_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='documento_identificacion',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
    ]
