# Generated by Django 3.1.4 on 2021-03-15 23:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0029_auto_20210315_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=250)),
        ),
    ]
