# Generated by Django 3.1.4 on 2021-03-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0030_auto_20210315_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaMemoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('similitud', models.FloatField()),
                ('usado_nutricion', models.BooleanField()),
                ('usado_ejercicio', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='RecomendadorMemoria',
        ),
    ]
