# Generated by Django 3.1.4 on 2021-03-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0031_auto_20210316_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='PreexistenciaMedica',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
