# Generated by Django 3.1.4 on 2021-03-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0032_auto_20210322_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='user',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='correo_usuario',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoria',
            name='tipo_usuario',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
