# Generated by Django 3.1.4 on 2021-03-23 05:01

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0033_auto_20210322_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=datetimeutc.fields.DateTimeUTCField(),
        ),
    ]
