# Generated by Django 3.1.4 on 2021-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynex_app', '0034_auto_20210323_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejercicio',
            name='generador',
            field=models.TextField(default='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='generador',
            field=models.TextField(default='content'),
            preserve_default=False,
        ),
    ]
